name: fastiapi-mongo-db
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
  mongo:
    image: mongo:6.0.6
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data-db:/data/db
volumes:
  mongo-data-db:
